name: Spellcheck and Alphabetical
on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Spellcheck Action
        uses: rojopolis/spellcheck-github-actions@0.34.0
        with:
          config_path: spellcheck.yaml
      - name: Ensure wordlist is alphabetized
        run: |
          sort --version
          LC_COLLATE='en_US.UTF-8' sh -c "cat wordlist.txt | sort -c"
          [ -z "$(uniq -D wordlist.txt)" ]
